version: '3.8'

services:
  # SQL Database (User Service)
  postgres:
    image: postgres:15-alpine
    container_name: messenger_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: messenger_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # NoSQL Database (Chat Service)
  mongo:
    image: mongo:6.0
    container_name: messenger_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data:
